name: Download XanMod 6.18.2

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download x64v3
        run: |
          mkdir -p kernel/6.18.2-x64v3-xanmod
          cd kernel/6.18.2-x64v3-xanmod
          wget --content-disposition "https://sourceforge.net/projects/xanmod/files/releases/main/6.18.2-xanmod1/6.18.2-x64v3-xanmod1/linux-image-6.18.2-x64v3-xanmod1_6.18.2-x64v3-xanmod1-0~20251218.g9f068d0_amd64.deb/download"
          wget --content-disposition "https://sourceforge.net/projects/xanmod/files/releases/main/6.18.2-xanmod1/6.18.2-x64v3-xanmod1/linux-libc-dev_6.18.2-x64v3-xanmod1-0~20251218.g9f068d0_amd64.deb/download"
          wget --content-disposition "https://sourceforge.net/projects/xanmod/files/releases/main/6.18.2-xanmod1/6.18.2-x64v3-xanmod1/linux-headers-6.18.2-x64v3-xanmod1_6.18.2-x64v3-xanmod1-0~20251218.g9f068d0_amd64.deb/download"

      - name: Download x64v2
        run: |
          mkdir -p kernel/6.18.2-x64v2-xanmod
          cd kernel/6.18.2-x64v2-xanmod
          wget --content-disposition "https://sourceforge.net/projects/xanmod/files/releases/main/6.18.2-xanmod1/6.18.2-x64v2-xanmod1/linux-image-6.18.2-x64v2-xanmod1_6.18.2-x64v2-xanmod1-0~20251218.g9f068d0_amd64.deb/download"
          wget --content-disposition "https://sourceforge.net/projects/xanmod/files/releases/main/6.18.2-xanmod1/6.18.2-x64v2-xanmod1/linux-libc-dev_6.18.2-x64v2-xanmod1-0~20251218.g9f068d0_amd64.deb/download"
          wget --content-disposition "https://sourceforge.net/projects/xanmod/files/releases/main/6.18.2-xanmod1/6.18.2-x64v2-xanmod1/linux-headers-6.18.2-x64v2-xanmod1_6.18.2-x64v2-xanmod1-0~20251218.g9f068d0_amd64.deb/download"

      - name: Commit
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add kernel
          git commit -m "add xanmod 6.18.2" || echo "no changes"
          git push
